### ISSUE TITLE
NameError: name 'opt_func' is not defined

### ISSUE THREAD

**Issue by chho-work** [JoshVarty/SelfSupervisedLearning#10]
Thanks for sharing the code!
I am using Colab to run "01_Inpainting_ImageWang.ipynb".
When I tried to run the cell that starts with "plotResultsCallback = PlotResultsAfterEpoch()",
I encountered with the below error output.  I removed "opt_func=opt_func" and it worked, even though with different training and validation loss.  

Pls kindly advise what I am doing wrong!  Many thanks!

---------------------------------------------------------------------------
"""
NameError                                 Traceback (most recent call last)

<ipython-input-34-e1a74fcf5541> in <module>()
      1 plotResultCallback = PlotResultAfterEpoch()
      2 
----> 3 learn = unet_learner(dbunch, model, pretrained=False, opt_func=opt_func, metrics=[], loss_func=MSELoss())
      4 
      5 if fp16: learn = learn.to_fp16()

NameError: name 'opt_func' is not defined
"""

**Comment by JoshVarty** [comment]
That's strange. Make sure you're on the latest version of `master`. `opt_func` should be set in cell two here: https://github.com/JoshVarty/SelfSupervisedLearning/blob/master/01_InpaintingImageWang/01_Inpainting_ImageWang.ipynb

What values do you get printed from cell 2? I see:

```
lr 0.008
size 128
sqrmom 0.99
mom 0.9
eps 1e-06
epochs 15
bs 64
opt ranger
sh 0.0
sa 0
sym 0
beta 0.0
act_fn <class 'fastai2.layers.Mish'>
fp16 0
pool (<function MaxPool at 0x7fde361deef0>,)
runs 1
model <function xresnet34 at 0x7fde35fee950>
```

**Comment by chho-work** [comment]
Thank you for your prompt reply!
I cloned the repo and ran "01_Inpainting_ImageWang.ipynb", it worked perfectly!
Initially, I re-typed "01_Inpainting_ImageWang.ipynb" to understand better the code.  I must have missed a line or something somewhere.  Sorry, beginners mistake!  
I will go back to my re-typed notebook and find out my error.
Next time I will be more careful and run the actual code first!  
Thank you for you kind attention!
